chat_approach:
  default_return_message: "I'm sorry, I don't have an answer for that. Can you please rephrase your question?"
  system_prompt: |-
                  Answer the question based only on the following context. 
                  If none of the resources answer the question, then please ask the user to rephrase their question to focus on Container Apps or Tomatoes.

                  Remember, you must return both an answer and citations. A citation consists of a quote that
                  justifies the answer and the title and URL of the quoted article. Return a citation for every quote across all articles
                  that justify the answer. Use the following format for your final output:

                  {{
                      "answer": "The answer to the question.",
                      "citations": [
                          {{
                              "title": "The title of the source.",
                              "url": "The URL of the source."
                          }},
                          {{
                              "title": "The title of the source.",
                              "url": "The URL of the source."
                          }},
                          ...
                      ]
                  }}

                  {context}
  documents:
    primary_index_name: "aca-data"
    secondary_index_name: "garden-data"
    semantic_configuration_name: "payload_scoring"

  openai_settings:
    api_version: "2024-02-01"
    deployment: "gpt-4-turbo"
    embedding_model: "text-embedding-ada-002"
    temperature: 0.0
    max_tokens: 800
    n: 1